<a href="https://colab.research.google.com/github/Aaaaddddyyyyyyyy/Data-Science/blob/main/Naive_bias_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd

In [11]:
df=pd.read_csv('/content/play_tennis.csv')
df.head()
df.drop(columns='day',inplace=True)
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [13]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [15]:
## probability of yes  otr no
py=9/14
pn=5/14
print(py,pn)

0.6428571428571429 0.35714285714285715